### PR TITLE
Logging for calculations of incremental builds

### PR DESCRIPTION
**Pull request by jglick**
The decision to do an incremental build or not, and if so which modules to include, is quite complex, and largely opaque to the user. This change allows the runtime behavior to be followed using the logger.

### CODE REVIEW

**Comment by jglick** [comment]
@reviewbybees and plugin maintainer(s), whoever you are; would like to get this old branch closed out somehow.

**Comment by KostyaSha** [comment]
@jglick PR build even not ended

**Comment by KostyaSha** [comment]
I trust @olamy ;)

**Comment by jglick** [comment]
(now subsumes #41)

**Comment by olamy** [comment]
ship it!! :-)

**Comment by KostyaSha** [comment]
:shipit: ? ;)

**Pull request merged**
