### PR TITLE
JENKINS-24832 Sets modules to NOT_BUILT if running after abort.

### PR DESCRIPTION
**Pull request by VVMichaelSawyer**
This causes all the modules running after an aborted build to have a status of NOT_BUILT. Ideally they would be labelled aborted, but this causes the entire build to be considered aborted if one module fails in a parallel build, and others are still building.

Please see https://issues.jenkins-ci.org/browse/JENKINS-24832

### CODE REVIEW

**Comment by olivergondza** [comment]
If I understand correctly, my fix that introduced this regression aborts all the module builds that are running at the time parent completed without checking parent's result.

The fix is supposed to make it `NOT_BUILD` instead. The information about the cause is preserved as a parent build result (to distinguish Failure/Abortion). :+1: from me.

**Comment by VVMichaelSawyer** [comment]
Yup, Oliver, you understand correctly. Having the status preserved in the build result means the job can send out correct emails, differentiating between Fail/Abort.

How soon can we see this merged in?

**Comment by christ66** [comment]
:+1:

**Comment by jglick** [comment]
Mild :-1: since I would prefer the status `ABORTED` for the submodule builds, as in #4, with a fix for the apparent problem with the parent status in the special case of `-T`. Presumably that problem and this fix is demonstrable in a new functional test.

I suspect [this code](https://github.com/jenkinsci/maven-plugin/blob/4609b712d86d90702dfbbb92c912cb9e6bc2ebb5/src/main/java/hudson/maven/MavenModuleSetBuild.java#L227-232) is the root of the problem: `ABORTED` is considered “worse” than `FAILURE` for purposes of computing the aggregate status, merely because of the ordinals of `Result`; we already have special handling for `NOT_BUILT` for this reason.

(All this said, the PR as it stands is probably an improvement over the current state.)

**Comment by VVMichaelSawyer** [comment]
We've been using this build for 4 months with no issues.

**Comment by jglick** [comment]
Recommend closing in favor of #79.

**Comment by aheritier** [comment]
Done @jglick

**Pull request closed without merging**
