### PR TITLE
JENKINS-43446 - java.lang.NoSuchFieldError: DEFAULT_USER_SETTINGS_FILE

### PR DESCRIPTION
**Pull request by tomerc**
I accidentally nuked the previous commits/PR.

These are all the changes in one clean commit

### CODE REVIEW

**Comment by tomerc** [comment]
@aheritier This is a clean pull request to replace the previous one

**Comment by aheritier** [comment]
TODO: We need to verify if the config file provider plugin is working correctly

**Comment by oleg-nenashev** [comment]
@aheritier Retested on 1.642 with the latest Config File Provider. It works fine. Same for the default versions. So I assume it is ready to go

**Comment by oleg-nenashev** [comment]
In longer term it makes sense to bump the core dependency to 1.642 (Config File Provider requires it) and to have more autotests

**Comment by olamy** [comment]
Hi I wonder when we will merge that?
The new maven version which introduce non backward compat change is used more and more.
Do you need a hand to help?

**Comment by aheritier** [comment]
I merged them @olamy 
https://github.com/jenkinsci/maven-interceptors/pull/11
https://github.com/jenkinsci/maven-plugin/pull/95

**Comment by tomdw** [comment]
@aheritier where can we follow up in which jenkins released version this will be included?

**Comment by aheritier** [comment]
I'll update JENKINS-43446
For now I'm shared to release an 1.5.2 with what we have which will be always better than 1.5.1 or try to wait to have a better visibility on the two important regressions we had in 1.5.1 : JENKINS-42962, JENKINS-43876
I think we have enough changes for a release and we can wait for others fixes. WDYT @olamy ?

**Comment by oleg-nenashev** [comment]
@aheritier @olamy +1 for the new release. Even with existing regressions, this change makes the situation better. Though it makes sense to add warning about regressions to the changelog.

I have one of the regressions in my shortlist, but my "short"list already requires memory pagination, no ETA :(

**Pull request merged**
