### PR TITLE
Update link and description to match Jenkins 2. Source of confusion i…

### PR DESCRIPTION
**Pull request by cbuechler**
…n ticket JENKINS-34743

### CODE REVIEW

**Comment by cbuechler** [comment]
The reason for the check failure isn't clear to me, is there a problem with the PR, or was there an issue with the test at the time? 

Admittedly this was about 5 minutes into my first look at any Jenkins source, but it seems like an innocuous enough change that it wouldn't break the build.

**Comment by olivergondza** [comment]
It seems to have nothing to do with your changes.

**Comment by aheritier** [comment]
Same goal here than PR #67

**Comment by aheritier** [comment]
Like #67 as far as the plugin can be used in 1.x and 2.x we should use a parameter for URL and compute it based on the version of Jenkins

**Comment by aheritier** [comment]
Superseded by #82 which keeps the compatibility for Jenkins 1.x users

**Pull request closed without merging**
