### PR TITLE
JENKINS-57119: Add socket keepalive so idle half-closed TCP connectio…

### PR DESCRIPTION
**Pull request by glavoie**
…ns do not leak forever.

https://issues.jenkins-ci.org/browse/JENKINS-57119

### CODE REVIEW

**Comment by glavoie** [comment]
@jglick thank you for the feedback.

I added an extra comment with explanation on the TCP KeepAlive in the Jira ticket.

We've already started to move away from this plugin in favor of pipelines, but unfortunately most of our jobs (hundreds) are still tied to it, hence the expectation for a fix. 

It appears that I can't merge this PR as the CI check failed for a reason that seems outside of the scope of this change: ```13:13:41  java.io.FileNotFoundException: /home/jenkins/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.pom.lastUpdated (Permission denied)```

**Comment by jglick** [comment]
Yes the CI failure looks like flaky build infrastructure. I am refreshing things in #127 and will keep a lookout for similar problems.

**Comment by glavoie** [comment]
When this is merge, can any ETA for a release?

**Comment by jglick** [comment]
Better ask the maintainer, @olamy last I checked.

**Comment by olamy** [comment]
@glavoie what about an option? 
to keep backward compat and if it breaks in some env (agree not sure how :) but this worked as is for so long time now)
```
public static boolean keepAlive = Boolean.getBoolean("jenkins.maven.keepAlive");
```
And you can use this field?

**Comment by glavoie** [comment]
@olamy I don't mind the system property to activate this, though I believe that every TCP connection should have some sort of operation timeout/keepalive by default. I've had to diagnose too many hung application/connection issues in the past caused by flaky network. :) 

This said, this system property should be set on the Jenkins master? I'm curious on how it would be propagated to the slave. I have yet to dig into how remoting works and the issue appears on slaves.

**Comment by olamy** [comment]
@glavoie good catch :) so let's merge as is it shouldn't break anything

**Comment by glavoie** [comment]
Thank you!

**Pull request merged**
