### PR TITLE
JENKINS-32635: Fix retrieving ignoreUnsuccessfulUpstreams from form

### PR DESCRIPTION
**Pull request by azherebtsov**
submmit

ignoreUnsuccessfulUpstreams parameter should be captured within triggerByDependency
configuration in the form JSON

### CODE REVIEW

**Comment by azherebtsov** [comment]
Dear @aheritier this pull request is the same as was https://github.com/jenkinsci/maven-plugin/pull/71 but rebased on top of current master and fixed. I tested it on localhost jenkins (last build till today 09/01) and it works fine

**Comment by aheritier** [comment]
Thanks a lot @azherebtsov I will try to review/test/merge it tomorrow

**Comment by aheritier** [comment]
Hi @azherebtsov, thanks a lot, I confirm the bug related to JENKINS-32635 and your PR is correctly fixing it.

**Comment by azherebtsov** [comment]
Hi @aheritier, thank you for your feedback! Have a good day!

**Pull request merged**
