### PR TITLE
fix link for Maven installation configuration

### PR DESCRIPTION
**Pull request by SubOptimal**
On a fresh Jenkins installation where Maven is not recognized a warning is displayed

> Jenkins needs to know where your Maven is installed.                                    
Please do so from <a href="{0}/configure" target="_new">the system configuration</a>.   

But the Maven installation needs to be configured at `/configureTools`

### CODE REVIEW

**Comment by aheritier** [comment]
I agree it's annoying. We should do this in a version compatible only with Jenkins 2+ Or we need a way to dynamically provide the path. any idea @daniel-beck @jenkinsci/code-reviewers ?

**Comment by daniel-beck** [comment]
Messages can be parameterized, and you can determine the current Jenkins version in code, passing the URL to the correct form.

**Comment by aheritier** [comment]
You're right, I think it is the best solution to adopt @daniel-beck

**Comment by aheritier** [comment]
Superseded by #82 which keeps the compatibility for Jenkins 1.x users

**Pull request closed without merging**
