### PR TITLE
[JENKINS-40949] MavenMultiModuleTest#symlinksUpdated are failing against jenkins >=2.X 

### PR DESCRIPTION
**Pull request by raul-arabaolaza**
[ JENKINS-40949](https://issues.jenkins-ci.org/browse/JENKINS-40949)

This way the test works with the same guarantees for 1.x series and works for 2.x series

@reviewbybees

### CODE REVIEW

**Comment by varyvol** [comment]
🐝

**Comment by armfergom** [comment]
🐝

**Comment by aheritier** [comment]
🐝

**Comment by aheritier** [comment]
@reviewbybees done

**Pull request merged**
