### PR TITLE
Maven plugin is not being installed by default starting from Jenkins 2

### PR DESCRIPTION
**Pull request by oleg-nenashev**
The text appears in the Plugin manager, and it may be misleading

@reviewbybees @aheritier

### CODE REVIEW

**Comment by aheritier** [comment]
Crappy test. Not related to the PR. :bee: for the PR

**Comment by jglick** [comment]
(And at this point I think no one cares that it used to be a part of Jenkins core. Ancient history.)

**Comment by aheritier** [comment]
WDYT of the update I did @jglick @oleg-nenashev @olamy ?

**Comment by aheritier** [comment]
yes random test failure :( @jglick

**Comment by oleg-nenashev** [comment]
> (And at this point I think no one cares that it used to be a part of Jenkins core. Ancient history.)

I have thought about it, but decided to remove only the 100% wrong part. Polish needs massive polishing anyway

**Pull request merged**
