### PR TITLE
[JENKINS-38736] Update Sisu Inject

### PR DESCRIPTION
**Pull request by jglick**
Intended to avoid a regression if and when https://github.com/jenkinsci/jenkins/pull/2568 is merged. Tested only to the extent that `RedeployPublisherTest.testTarGzMaven3` fails as in https://github.com/google/guice/issues/899 using Guice 4.0 final unless Sisu Inject is also updated.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Works for me

**Comment by stephenc** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
🐝 
@reviewbybees done

**Comment by aheritier** [comment]
I will review it. Last time I tried, I had some issues :(
But the problem is how tests are written to validate them with different maven versions :(
Why CI isn't validating this ...
Otherwise I'm +1 with the change

**Comment by KostyaSha** [comment]
> Why CI isn't validating this ...

@daniel-beck @rtyler infra?

**Comment by daniel-beck** [comment]
@KostyaSha Neither of us runs jenkins.ci.c.c (AFAIU @aheritier does), and without Jenkinsfile there's no build on ci.j.io.

**Comment by KostyaSha** [comment]
6 builds are running against PR https://jenkins.ci.cloudbees.com/job/plugins/job/maven-plugin/

**Comment by KostyaSha** [comment]
1 failed, 1 ok, 4 running..

**Comment by aheritier** [comment]
@daniel-beck yes I have in my todo to host the build on ci.jenkins.io ...
@KostyaSha I don't understand why it was triggered 6 times :(

**Comment by KostyaSha** [comment]
2 bad 3 ok, keeping in mind how slow is build i would expect build failures. 1 ok is win :)

**Comment by KostyaSha** [comment]
@aheritier ok to merge and release?

**Comment by aheritier** [comment]
@KostyaSha merge yes. Release I need to verify. I think I had something to finish.

**Pull request merged**
