### PR TITLE
Do not encourage using -DskipTests

### PR DESCRIPTION
**Pull request by kamilszymanski**

### CODE REVIEW

**Comment by aheritier** [comment]
@kamilszymanski +1000 but perhaps we could use another property just to show that they are supported like `-DinstallAtEnd=true` WDYT ?

**Comment by kamilszymanski** [comment]
Good point, I've added example with system property

**Comment by aheritier** [comment]
@kamilszymanski you will hate me but I think it is better to use the right case : `java.net.preferIPv4Stack`
https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html
I don't remember if such system property is case sensitive

**Comment by kamilszymanski** [comment]
nice catch @aheritier 
I just fixed that

**Pull request merged**
