### PR TITLE
[JENKINS-25406] Downgrade ISE to log warning

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-25406](https://issues.jenkins-ci.org/browse/JENKINS-25406)

Under circumstances yet to be identified, the Maven plugin sometimes tries to set the build result after the build is `COMPLETED`, which is illegal. Until 1.586 Jenkins core silently let it do so unless you happened to be running with `-ea`. As of 1.587 this becomes an `IllegalStateException`, which alerted us to the problem but might be breaking more important things (unclear what the impact is). Downgrading this to a warning in the log and just ignore the attempt to change the build result.

@reviewbybees

### CODE REVIEW

**Comment by KostyaSha** [comment]
Shouldn't break anything, so :+1:

**Comment by jglick** [comment]
_Could_ break something, in case the Maven plugin was really relying on being able to change build status after completion.

Build timed out on CI. I will set the project to use a faster machine class and will file a separate PR for an unrelated test failure.

**Comment by KostyaSha** [comment]
@jglick then lets comment return and grad logging results first?

**Comment by jglick** [comment]
(now subsumes #41)

**Comment by jglick** [comment]
> lets comment return and grab logging results first

I am not sure what that would tell us. We already have the stack traces, and they do not point to a clear culprit. Need a way to reproduce the problem.

**Comment by jglick** [comment]
Hmm, for some reason PR builds do not seem to be being triggered at all ATM.

**Comment by KostyaSha** [comment]
@jglick push slowly :laughing:

**Comment by tfennelly** [comment]
:+1: looks fine to me

**Pull request merged**
