### PR TITLE
pass maven.multiModuleProjectDirectory option to maven argument builder

### PR DESCRIPTION
**Pull request by kofemann**
as it done by regular mvn command.

Signed-off-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>

### CODE REVIEW

**Comment by bigdaz** [comment]
@olamy I'm working to make [Gradle Enterprise](gradle.com) compatible with the Maven job type in Jenkins. GE for Maven is implemented as a Maven Extension, but we also rely on the `maven.multiModuleProjectDirectory` at times. So I thought I'd first see if I can test this PR before attempting something more ambitious.

Do you have any hints/advice on how to develop this plugin, in particular how to test the functionality in Jenkins with a real Maven project? I've tried loading the plugin in various ways (replace the Jar directly, install the plugin as an `hpi` file, `mvn hpi:run`) but I don't see the "Maven" build type when attempting to add a new item to Jenkins. What's the best way to test local changes?

Thanks in advance.

**Comment by olamy** [comment]
@bigdaz you should be able to use `mvn hpi:run` in the project directory and go to `http://localhost:8080/jenkins` or `mvn package -DskipTests` and copy the generated hpi file to `$JENKINS_HOME/plugins` (Jenkins restart needed) 
HTH otherwise let me know.

**Comment by bigdaz** [comment]
@olamy thanks for the pointers. I could have sworn that these steps were not working (Maven job type wasn't appearing when I did `hpi:run`), but now I try again everything is working as expected. 

I still have no idea how to get the `Maven3Builder` to load project-level extensions. But I'll keep digging. I'll open a new issue to facilitate discussion.

**Comment by olamy** [comment]
@bigdaz look at https://github.com/jenkinsci/lib-jenkins-maven-embedder this might need some changes as well

**Comment by bigdaz** [comment]
Thanks @olamy. Do you have any specific pointers/ideas on what might be causing the extension-loading issue with the Maven Embedder? 

 I'd like to see this issue fixed, but I have zero knowledge of Maven internals and while I'm unlikely to find time to work on it without some guidance from someone who does. In the meantime, we are recommending that our potential customers switch to https://plugins.jenkins.io/pipeline-maven/.

**Pull request closed without merging**
