### PR TITLE
JENKINS-7010: Maven settings configured at Maven job level aren't used inside the promotion step

### PR DESCRIPTION
**Pull request by aheritier**

### CODE REVIEW

**Comment by aheritier** [comment]
please @reviewbybees

**Comment by oleg-nenashev** [comment]
:bee: , but may be a bit hacky. There's an extension point in Promoted Builds plugin, which allows to determine the source, but it would require a mandatory dependency

**Comment by aheritier** [comment]
Yes @oleg-nenashev I cannot have a dependency here, even if it is optional because it creates a cycle because the promoted build plugin depends on the maven plugin. A clean fix would be to make the publisher extensible to define where to get the project and to override it in the task on the promotion side. But it will require 2 fixes, 2 releases, a mandatory upgrade of the maven plugin in the promotion dependencies ...

**Comment by aheritier** [comment]
No more feedbacks ?

**Comment by aheritier** [comment]
@reviewbybees done

**Comment by aheritier** [comment]
@jglick could it be merged please ? It was open for review for 2 weeks. Thx

**Comment by jglick** [comment]
Ask @olamy. I am not a maintainer of this plugin.

**Comment by aheritier** [comment]
thx @olamy

**Pull request merged**
