### PR TITLE
Set EnvVars in redeploy and expand variables in properties

### PR DESCRIPTION
**Pull request by cpfeiffer**
Make it symmetric with normal deploy, otherwise builds relying on this will fail.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
> Make it symmetric with normal deploy, otherwise builds relying in this will fail.

Is there a related JIRA ticket?

**Comment by cpfeiffer** [comment]
I've opened this ticket: https://issues.jenkins-ci.org/browse/JENKINS-48861

**Comment by oleg-nenashev** [comment]
I will try to review it next week. My proposal would be to ship the master branch without it for now, because we have a serious JEP-200 regression

**Comment by cpfeiffer** [comment]
The Maven build already receives these variables, so there's nothing to protect anymore in the redeploy step. If there should be an opt-out, it should be configurable in both cases.

**Comment by cpfeiffer** [comment]
Thanks! Unfortunately my colleague pushed another fix to this branch today. I'll move this out to a different PR.

**Comment by cpfeiffer** [comment]
FWIW, the remaining test failure is unrelated to our changes:
`Caused by: java.lang.ClassNotFoundException: org.apache.maven.doxia.siterenderer.DocumentContent`

**Comment by daniel-beck** [comment]
@github-actions You suck.

@olamy Please consider maintaining your plugin instead of setting up pointless spam.

**Pull request closed without merging**
